app.websocket.url=wss://imposter.wil.gg/ws/lobby/
app.cors.allowed-origins=https://imposter.wil.gg

logging.file.name=logs/imposter.log
logging.logback.rollingpolicy.file-name-pattern=logs/imposter-%d{yyyy-MM-dd}-%i.log
logging.logback.rollingpolicy.max-history=14