spring.application.name=imposter
spring.banner.location=classpath:banner.txt
build-version=@project.version@
spring.profiles.active=prod

app.api.refill-time=10
app.api.token-count=5

app.cors.allowed-origins=https://imposter.wil.gg

app.game.imposter.answering-phase-duration.default=60
app.game.imposter.answering-phase-duration.max=180
app.game.imposter.answering-phase-duration.min=15
app.game.imposter.discussion-phase-duration.default=15
app.game.imposter.discussion-phase-duration.max=60
app.game.imposter.discussion-phase-duration.min=5
app.game.imposter.max-rounds.default=3
app.game.imposter.max-rounds.max=7
app.game.imposter.max-rounds.min=1
app.game.imposter.voting-phase-duration.default=60
app.game.imposter.voting-phase-duration.max=180
app.game.imposter.voting-phase-duration.min=15

app.game.thread.sleep-inaccuracy=5000000
app.game.thread.tps=10

app.lobby.code.allowed-chars=ABCDEFGHIJKLMNOPQRSTUVWXYZ
app.lobby.code.length=6
app.lobby.code.max-attempts=100
app.lobby.timeout=3000

app.server.mode=BOTH

app.websocket.max-connections=10
app.websocket.messages-per-second=10
app.websocket.max-size=8192
app.websocket.url=wss://imposter.wil.gg/ws/lobby/