spring.application.name=imposter
spring.banner.location=classpath:banner.txt
build-version=@project.version@
spring.profiles.active=prod

app.cors.allowed-origins=https://imposter.wil.gg

app.websocket.max-connections=10
app.websocket.messages-per-second=10
app.websocket.max-size=8192
app.websocket.url=wss://imposter.wil.gg/ws/lobby/