app.cors.allowed-origins=http://localhost:3000

app.server.public-url=http://localhost:8081

app.websocket.url=ws://localhost:8080/ws/lobby/

spring.data.redis.host=localhost
spring.data.redis.port=6379