spring.application.name=imposter
spring.banner.location=classpath:banner.txt
build-version=@project.version@
spring.profiles.active=prod

app.api.refill-time=10
app.api.token-count=5

app.cors.allowed-origins=https://imposter.wil.gg

app.lobby.code.allowed-chars=ABCDEFGHIJKLMNOPQRSTUVWXYZ
app.lobby.code.length=6
app.lobby.code.max-attempts=100
app.lobby.timeout=3000

app.websocket.max-connections=10
app.websocket.messages-per-second=10
app.websocket.max-size=8192
app.websocket.url=wss://imposter.wil.gg/ws/lobby/