package gg.wil.imposter.game.scheduler;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.PriorityQueue;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

public class GameScheduler {

    private final Logger logger;
    private AtomicInteger idCounter = new AtomicInteger(0);

    // linked list of unsorted tasks
    private volatile GameTask head = new GameTask();
    private AtomicReference<GameTask> tail = new AtomicReference<>(head);

    // compare by next run, then creation time
    private final PriorityQueue<GameTask> taskQueue = new PriorityQueue<>(5, Comparator.comparingLong(GameTask::getNextRun).thenComparingLong(GameTask::getCreationTime));
    private final PriorityQueue<GameTask> taskQueueMillis = new PriorityQueue<>(5, Comparator.comparingLong(GameTask::getNextRunNano).thenComparingLong(GameTask::getCreationTime));
    private final ConcurrentHashMap<Integer, GameTask> tasks = new ConcurrentHashMap<>();

    private int currentTick = 0;

    public GameScheduler(String identifier) {
        this.logger = LoggerFactory.getLogger("GameScheduler - " + identifier);
    }

    public void gameThreadTick() {
        this.currentTick++;
        addUnsortedTasksToQueue();
        runQueuedTasks();
        runQueuedTasksMillis();
    }

    private void runQueuedTasks() {
        final List<GameTask> rescheduledTasks = new ArrayList<>();
        while(!taskQueue.isEmpty() && taskQueue.peek().getNextRun() <= this.currentTick) {
            final GameTask task = taskQueue.remove();
            if(!attemptRunTask(task)) continue;

            // reschedule task
            final long period = task.getPeriod();
            if(period > 0) {
                task.setNextRun(this.currentTick + period);
                rescheduledTasks.add(task);
            } else {
                tasks.remove(task.getId());
            }

            addUnsortedTasksToQueue();
        }
        taskQueue.addAll(rescheduledTasks);
    }

    private void runQueuedTasksMillis() {
        final List<GameTask> rescheduledTasks = new ArrayList<>();
        while(!taskQueueMillis.isEmpty() && taskQueueMillis.peek().getNextRunNano() <= System.nanoTime()) {
            final GameTask task = taskQueueMillis.remove();
            if(!attemptRunTask(task)) continue;

            // reschedule task
            final long period = task.getPeriod();
            if(period > 0) {
                task.setNextRunNano(System.nanoTime() + (period * 1000000L));
                rescheduledTasks.add(task);
            } else {
                tasks.remove(task.getId());
            }

            addUnsortedTasksToQueue();
        }
        taskQueueMillis.addAll(rescheduledTasks);
    }

    private boolean attemptRunTask(GameTask task) {
        if(task.isCancelled()) {
            addUnsortedTasksToQueue();
            return false;
        }

        // run task
        try {
            task.run();
        } catch (Throwable t) {
            this.logger.error("Exception generated by task with ID {}", task.getId(), t);
        }
        return true;
    }

    private void addUnsortedTasksToQueue() {
        GameTask head = this.head;
        GameTask task = head.getNext();
        GameTask lastTask = head;

        // queue all unsorted tasks
        while(task != null) {
            if(task.getId() == -1) {
                task.run();
            }  else if(!task.isCancelled()) {
                if(task.getNextRunNano() == -1) taskQueue.add(task);
                else taskQueueMillis.add(task);
                tasks.put(task.getId(), task);
            }

            lastTask = task;
            task = task.getNext();
        }

        // unlink all tasks that have been queued
        while(task != lastTask) {
            task = head;
            head = task.getNext();
            task.setNext(null);
        }
        this.head = lastTask;
    }

    private int getNextId() {
        int id;
        do { id = this.idCounter.incrementAndGet();
        } while(tasks.containsKey(id));

        return id;
    }

    private void addTask(final GameTask task, long delay) {
        if(delay < 0) delay = 0;

        task.setNextRun(this.currentTick + delay);
        final GameTask lastTask = tail.getAndSet(task);
        lastTask.setNext(task);
    }

    private void addTaskMillis(final GameTask task, long delayMillis) {
        task.setNextRunNano(System.nanoTime() + (delayMillis * 1000000L));
        final GameTask lastTask = tail.getAndSet(task);
        lastTask.setNext(task);
    }

    public GameTask runTask(Runnable task) {
        return this.runTaskTimer(task, GameTask.NO_REPEATING, 0L);
    }

    public GameTask runTaskLater(Runnable task, long delay) {
        return this.runTaskTimer(task, GameTask.NO_REPEATING, delay);
    }

    public GameTask runTaskTimer(Runnable task, long period) {
        return this.runTaskTimer(task, period, 0L);
    }

    public GameTask runTaskTimer(Runnable task, long period, long delay) {
        final GameTask taskInstance = new GameTask(this.getNextId(), task, period);
        this.addTask(taskInstance, delay);
        return taskInstance;
    }

    public GameTask runTaskLaterMillis(Runnable task, long delayMillis) {
        return this.runTaskTimerMillis(task, GameTask.NO_REPEATING, delayMillis);
    }

    public GameTask runTaskTimerMillis(Runnable task, long periodMillis) {
        return this.runTaskTimerMillis(task, periodMillis, 0L);
    }

    public GameTask runTaskTimerMillis(Runnable task, long periodMillis, long delayMillis) {
        final GameTask taskInstance = new GameTask(this.getNextId(), task, periodMillis);
        this.addTaskMillis(taskInstance, delayMillis);
        return taskInstance;
    }

    public void cancelTask(final int taskID) {
        if(taskID <= 0) return;

        GameTask task = tasks.get(taskID);
        if(task != null) task.cancel();
    }

    public void cancelAllTasks() {
        this.tasks.values().forEach(GameTask::cancel);
    }
}
